const sections = [
  { keywords: ["right", "rights", "member", "membership", "belong"], text: `Section 6: Membership - All duly matriculated full-time students of Faculty of Computing and Information Technology are eligible members. Members forfeit membership if: graduated, found in secret cult, or rusticated. Section 7: Rights of Members - Every member shall: enjoy Association facilities, participate at congress, vote and be voted for (except sandwich/part-time students), have rights to information, receive ID card and constitution copy.` },
  { keywords: ["csrc", "legislative", "representative", "council", "honourable", "speaker", "clerk", "whip"], text: `Section 13-23: CSRC - Computing Students Representative Council holds legislative power. Consists of 10 honourables per department, max 3 per level. Speaker is head, has no vote except tie. Deputy Speaker acts in speaker's absence. Clerk is administrative officer. Chief Whip is law enforcement officer. Quorum is simple majority (half plus one). Sitting at least once monthly, notice 48 hours before. Absence from 3 consecutive sittings without notice forfeits seat.` },
  { keywords: ["sec", "executive", "president", "vice", "secretary", "treasurer", "welfare", "social", "sport", "pro", "public relation"], text: `Section 24-28: SEC - Student Executive Council holds executive power. Officers: President (head, no vote except tie, signs Central Account), Vice President (assists president, meets HOCs twice monthly), General Secretary (administrative duties, keeps minutes), Welfare Director, Social Director (accounts to FinSec within 48hrs), Financial Secretary (receives all money, remits to treasurer within 48hrs, signs accounts), Treasurer (keeps imprest max N5000, custodian of cheque books), Sport Director, Assistant General Secretary, PRO. Quorum is simple majority.` },
  { keywords: ["congress", "highest", "dissolve", "resolution", "confidence", "quorum"], text: `Section 29-34: Congress - Highest decision making body of the union. Has final say on all matters. Can dissolve SEC and/or CSRC. Pass motions of confidence or no confidence. Called by Speaker, President, or written request of at least 50 members across all levels. Quorum is 50 members across all levels. If quorum not formed twice, any number on third occasion forms congress.` },
  { keywords: ["fund", "finance", "money", "account", "budget", "share", "formula", "imprest", "receipt", "treasurer", "auditor"], text: `Section 47-59: Finances - Financial year is whole academic session. Sources: Union Due, Departmental Levy, Gifts/Donations. Three accounts: Central Account (signatories: President, Auditor General, Financial Secretary), SEC Account (signatories: President, Financial Secretary, Treasurer), CSRC Account (signatories: Speaker, Clerk). Sharing formula: SEC 64%, CSRC 35%, Auditor General 1%. Treasurer imprest max N3,000. Clerk imprest max N2,000. No payment above N1,000 through imprest. Budget presented within 21 days of inauguration, operative only after CSRC approval.` },
  { keywords: ["election", "vote", "contest", "campaign", "cgpa", "eligib", "iec", "ballot", "aspirant", "nomina"], text: `Section 66-94: Electoral Act - IEC is independent, cannot be partial. Campaigns must be well-mannered, no harassment, posters only on notice boards not walls, campaigns end 24hrs before voting. Eligibility to vote: paid dues, matriculated, full-time (no part-time or sandwich). Eligibility to contest: must not have criminal conviction, cult membership, or be guilty of malpractice. President/VP/Speaker/General Secretary require CGPA of 3.00 minimum and must have served in CSRC/SEC/committee. Other SEC positions require CGPA 2.50 minimum. Speaker must have served as Honourable for at least TWO sessions. Voting duration max 5 hours, 9am-3pm. Results declared only by IEC chairman.` },
  { keywords: ["remove", "removal", "resign", "resignation", "impeach", "dissolv", "terminat"], text: `Section 63-65: Termination - Resignation requires written notice at least 2 weeks before. President/Speaker resignation goes to Clerk of CSRC. CSRC members' resignation goes to President. Removal by simple majority resolution of all CSRC members after consulting constituencies. Officer must hand over properties and render account within one week. Resignation or removal does NOT absolve from liabilities.` },
  { keywords: ["amend", "amendment", "change", "modify", "constitution"], text: `Section 95: Amendment - CSRC can amend with two-thirds (2/3) majority approval. Process: Call for memorandum, Public hearing, Constitution drafting, 1st and 2nd reading by CSRC, Adoption by congress. Amended constitution pasted at all levels at least one week before congress.` },
  { keywords: ["committee", "standing", "adhoc", "ad-hoc", "academic", "tutorial", "audit", "disciplin", "ethics", "tech"], text: `Section 40-46: Committees - Standing committees: Academic and Tutorial (chaired by VP), Budgetary and Finance (chaired by Clerk, Auditor General is automatic member), IEC (set up 6 weeks before exams), IAC (set up 6 weeks before end of session, can indict and sue members), Welfare, Social and Cultural, Sports, Ethics and Disciplinary (3 members per level), Tech Committee. Ad-hoc committees constituted by CSRC as needed, funded by CSRC, dissolved when duty is accomplished.` },
  { keywords: ["transition", "handover", "swear", "inaugur", "oath"], text: `Section 60-62 and 94: Transition - Transition period begins when IEC is inaugurated, 6 weeks before second semester exams. SEC and CSRC remain as transitional government. Any aspirant from incumbent SEC or CSRC must resign at least 7 days before transition period. Formal handover ceremony required. Oath of office administered by IEC chairman.` },
  { keywords: ["patron", "staff adviser", "honorary", "honorary member"], text: `Section 8-10: Patrons, Staff Advisers, Honorary Members - Patrons nominated by SEC, approved by CSRC, max 3 per session. Staff Advisers max 3: two Academic Staff (min PhD) and one Non-Academic staff. Honorary members are past members nominated by SEC and ratified by CSRC.` },
  { keywords: ["code of conduct", "conduct", "officer", "benefit", "gift", "interest"], text: `Second Schedule - Code of Conduct: No officer shall let personal interest conflict with duties. No officer shall accept benefits or gifts for discharge of duties. No officer shall be in societies incompatible with office dignity. No officer shall do unlawful acts prejudicial to others rights. Breaches reported to CSRC.` },
];

function retrieveRelevantSections(question) {
  const q = question.toLowerCase();
  const matched = sections.filter(section =>
    section.keywords.some(keyword => q.includes(keyword))
  );

  if (matched.length === 0) {
    // Return a general summary if nothing matches
    return `NACOS-LASU is the Nigerian Association of Computing Students, Lagos State University Chapter. Its motto is Excellence Through Innovation. It has three arms: the CSRC (legislative), SEC (executive), and Congress (highest decision-making body). The constitution covers membership rights, elections, finances, committees, and conduct of officers.`;
  }

  return matched.map(s => s.text).join("\n\n");
}

module.exports = { retrieveRelevantSections };